// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package globalpinggo

import (
	"bytes"
	"context"
	"fmt"
	"github.com/speakeasy-sdks/globalping-go/pkg/models/operations"
	"github.com/speakeasy-sdks/globalping-go/pkg/models/sdkerrors"
	"github.com/speakeasy-sdks/globalping-go/pkg/models/shared"
	"github.com/speakeasy-sdks/globalping-go/pkg/utils"
	"io"
	"net/http"
	"strings"
)

type probes struct {
	sdkConfiguration sdkConfiguration
}

func newProbes(sdkConfig sdkConfiguration) *probes {
	return &probes{
		sdkConfiguration: sdkConfig,
	}
}

// ListProbes - List currently connected probes
// Returns a list of all currently connected probes and their metadata.
func (s *probes) ListProbes(ctx context.Context) (*operations.ListProbesResponse, error) {
	baseURL := utils.ReplaceParameters(s.sdkConfiguration.GetServerDetails())
	url := strings.TrimSuffix(baseURL, "/") + "/v1/probes"

	req, err := http.NewRequestWithContext(ctx, "GET", url, nil)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("user-agent", fmt.Sprintf("speakeasy-sdk/%s %s %s %s", s.sdkConfiguration.Language, s.sdkConfiguration.SDKVersion, s.sdkConfiguration.GenVersion, s.sdkConfiguration.OpenAPIDocVersion))

	client := s.sdkConfiguration.DefaultClient

	httpRes, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	if httpRes == nil {
		return nil, fmt.Errorf("error sending request: no response")
	}

	rawBody, err := io.ReadAll(httpRes.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}
	httpRes.Body.Close()
	httpRes.Body = io.NopCloser(bytes.NewBuffer(rawBody))

	contentType := httpRes.Header.Get("Content-Type")

	res := &operations.ListProbesResponse{
		StatusCode:  httpRes.StatusCode,
		ContentType: contentType,
		RawResponse: httpRes,
	}
	switch {
	case httpRes.StatusCode == 200:
		switch {
		case utils.MatchContentType(contentType, `application/json`):
			var out []shared.Probe
			if err := utils.UnmarshalJsonFromResponseBody(bytes.NewBuffer(rawBody), &out, ""); err != nil {
				return nil, err
			}

			res.Probes = out
		default:
			return nil, sdkerrors.NewSDKError(fmt.Sprintf("unknown content-type received: %s", contentType), httpRes.StatusCode, string(rawBody), httpRes)
		}
	}

	return res, nil
}
