// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/globalping-go/pkg/models/shared"
	"net/http"
)

type CreateMeasurementResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Accepted
	CreateMeasurementResponse *shared.CreateMeasurementResponse
	Headers                   map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateMeasurementResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateMeasurementResponse) GetCreateMeasurementResponse() *shared.CreateMeasurementResponse {
	if o == nil {
		return nil
	}
	return o.CreateMeasurementResponse
}

func (o *CreateMeasurementResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *CreateMeasurementResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateMeasurementResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
