// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type GetMeasurementError struct {
	Message string `json:"message"`
	Type    string `json:"type"`
}

func (o *GetMeasurementError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *GetMeasurementError) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

// GetMeasurementResponseBody - Not Found
type GetMeasurementResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response      `json:"-"`
	Error_      GetMeasurementError `json:"error"`
}

var _ error = &GetMeasurementResponseBody{}

func (e *GetMeasurementResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
