// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DNSTestAnswer struct {
	// The record class.
	Class string `json:"class"`
	// The record domain name.
	Name string `json:"name"`
	// The record TTL in seconds.
	TTL int64 `json:"ttl"`
	// The record type.
	Type string `json:"type"`
	// The record value.
	Value string `json:"value"`
}

func (o *DNSTestAnswer) GetClass() string {
	if o == nil {
		return ""
	}
	return o.Class
}

func (o *DNSTestAnswer) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DNSTestAnswer) GetTTL() int64 {
	if o == nil {
		return 0
	}
	return o.TTL
}

func (o *DNSTestAnswer) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *DNSTestAnswer) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
