// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Timings struct {
	// The total query time in milliseconds.
	Total float64 `json:"total"`
}

func (o *Timings) GetTotal() float64 {
	if o == nil {
		return 0.0
	}
	return o.Total
}

type DNSTestHopResult struct {
	// The list of received resource records.
	Answers []DNSTestAnswer `json:"answers"`
	// The hostname or IP of the resolver that answered the query.
	Resolver string  `json:"resolver"`
	Timings  Timings `json:"timings"`
}

func (o *DNSTestHopResult) GetAnswers() []DNSTestAnswer {
	if o == nil {
		return []DNSTestAnswer{}
	}
	return o.Answers
}

func (o *DNSTestHopResult) GetResolver() string {
	if o == nil {
		return ""
	}
	return o.Resolver
}

func (o *DNSTestHopResult) GetTimings() Timings {
	if o == nil {
		return Timings{}
	}
	return o.Timings
}
