// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/globalping-go/pkg/utils"
)

type MeasurementMtrOptionsProtocol string

const (
	MeasurementMtrOptionsProtocolIcmp MeasurementMtrOptionsProtocol = "ICMP"
	MeasurementMtrOptionsProtocolTCP  MeasurementMtrOptionsProtocol = "TCP"
	MeasurementMtrOptionsProtocolUDP  MeasurementMtrOptionsProtocol = "UDP"
)

func (e MeasurementMtrOptionsProtocol) ToPointer() *MeasurementMtrOptionsProtocol {
	return &e
}

func (e *MeasurementMtrOptionsProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ICMP":
		fallthrough
	case "TCP":
		fallthrough
	case "UDP":
		*e = MeasurementMtrOptionsProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MeasurementMtrOptionsProtocol: %v", v)
	}
}

type MeasurementMtrOptions struct {
	Packets  *int64                         `default:"3" json:"packets"`
	Port     *int64                         `default:"80" json:"port"`
	Protocol *MeasurementMtrOptionsProtocol `default:"ICMP" json:"protocol"`
}

func (m MeasurementMtrOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MeasurementMtrOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *MeasurementMtrOptions) GetPackets() *int64 {
	if o == nil {
		return nil
	}
	return o.Packets
}

func (o *MeasurementMtrOptions) GetPort() *int64 {
	if o == nil {
		return nil
	}
	return o.Port
}

func (o *MeasurementMtrOptions) GetProtocol() *MeasurementMtrOptionsProtocol {
	if o == nil {
		return nil
	}
	return o.Protocol
}
