// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type MeasurementType string

const (
	MeasurementTypePing       MeasurementType = "ping"
	MeasurementTypeTraceroute MeasurementType = "traceroute"
	MeasurementTypeDNS        MeasurementType = "dns"
	MeasurementTypeMtr        MeasurementType = "mtr"
	MeasurementTypeHTTP       MeasurementType = "http"
)

func (e MeasurementType) ToPointer() *MeasurementType {
	return &e
}

func (e *MeasurementType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ping":
		fallthrough
	case "traceroute":
		fallthrough
	case "dns":
		fallthrough
	case "mtr":
		fallthrough
	case "http":
		*e = MeasurementType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MeasurementType: %v", v)
	}
}
