// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Probe struct {
	Location ProbeLocation `json:"location"`
	// A list of default DNS resolvers configured on the probe.
	Resolvers []string `json:"resolvers"`
	// An array of additional values that can be used to target the probe.
	// Probes hosted in [AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions)
	// and [Google Cloud](https://cloud.google.com/compute/docs/regions-zones#available) are automatically assigned the service region code.
	// Probes are also automatically assigned `datacenter-network` and `eyeball-network` tags to distinguish between datacenter and end-user locations.
	//
	Tags []string `json:"tags"`
	// Probe version.
	Version string `json:"version"`
}

func (o *Probe) GetLocation() ProbeLocation {
	if o == nil {
		return ProbeLocation{}
	}
	return o.Location
}

func (o *Probe) GetResolvers() []string {
	if o == nil {
		return []string{}
	}
	return o.Resolvers
}

func (o *Probe) GetTags() []string {
	if o == nil {
		return []string{}
	}
	return o.Tags
}

func (o *Probe) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}
