// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ProbeLocation struct {
	// An autonomous system number.
	Asn int64 `json:"asn"`
	// A city name in English.
	City      string        `json:"city"`
	Continent ContinentCode `json:"continent"`
	// An ISO 3166-1 alpha-2 country code.
	Country   string  `json:"country"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	// A network name.
	Network string `json:"network"`
	// A Geographic Region name based on the
	// UN [Standard Country or Area Codes for Statistical Use (M49)](https://unstats.un.org/unsd/methodology/m49/).
	//
	Region RegionName `json:"region"`
	// Only for US states. A two-letter state code based on ISO 3166-2.
	State *string `json:"state,omitempty"`
}

func (o *ProbeLocation) GetAsn() int64 {
	if o == nil {
		return 0
	}
	return o.Asn
}

func (o *ProbeLocation) GetCity() string {
	if o == nil {
		return ""
	}
	return o.City
}

func (o *ProbeLocation) GetContinent() ContinentCode {
	if o == nil {
		return ContinentCode("")
	}
	return o.Continent
}

func (o *ProbeLocation) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *ProbeLocation) GetLatitude() float64 {
	if o == nil {
		return 0.0
	}
	return o.Latitude
}

func (o *ProbeLocation) GetLongitude() float64 {
	if o == nil {
		return 0.0
	}
	return o.Longitude
}

func (o *ProbeLocation) GetNetwork() string {
	if o == nil {
		return ""
	}
	return o.Network
}

func (o *ProbeLocation) GetRegion() RegionName {
	if o == nil {
		return RegionName("")
	}
	return o.Region
}

func (o *ProbeLocation) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}
