// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RegionName - A Geographic Region name based on the
// UN [Standard Country or Area Codes for Statistical Use (M49)](https://unstats.un.org/unsd/methodology/m49/).
type RegionName string

const (
	RegionNameNorthernAfrica         RegionName = "Northern Africa"
	RegionNameEasternAfrica          RegionName = "Eastern Africa"
	RegionNameMiddleAfrica           RegionName = "Middle Africa"
	RegionNameSouthernAfrica         RegionName = "Southern Africa"
	RegionNameWesternAfrica          RegionName = "Western Africa"
	RegionNameCaribbean              RegionName = "Caribbean"
	RegionNameCentralAmerica         RegionName = "Central America"
	RegionNameSouthAmerica           RegionName = "South America"
	RegionNameNorthernAmerica        RegionName = "Northern America"
	RegionNameCentralAsia            RegionName = "Central Asia"
	RegionNameEasternAsia            RegionName = "Eastern Asia"
	RegionNameSouthEasternAsia       RegionName = "South-eastern Asia"
	RegionNameSouthernAsia           RegionName = "Southern Asia"
	RegionNameWesternAsia            RegionName = "Western Asia"
	RegionNameEasternEurope          RegionName = "Eastern Europe"
	RegionNameNorthernEurope         RegionName = "Northern Europe"
	RegionNameSouthernEurope         RegionName = "Southern Europe"
	RegionNameWesternEurope          RegionName = "Western Europe"
	RegionNameAustraliaAndNewZealand RegionName = "Australia and New Zealand"
	RegionNameMelanesia              RegionName = "Melanesia"
	RegionNameMicronesia             RegionName = "Micronesia"
	RegionNamePolynesia              RegionName = "Polynesia"
)

func (e RegionName) ToPointer() *RegionName {
	return &e
}

func (e *RegionName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Northern Africa":
		fallthrough
	case "Eastern Africa":
		fallthrough
	case "Middle Africa":
		fallthrough
	case "Southern Africa":
		fallthrough
	case "Western Africa":
		fallthrough
	case "Caribbean":
		fallthrough
	case "Central America":
		fallthrough
	case "South America":
		fallthrough
	case "Northern America":
		fallthrough
	case "Central Asia":
		fallthrough
	case "Eastern Asia":
		fallthrough
	case "South-eastern Asia":
		fallthrough
	case "Southern Asia":
		fallthrough
	case "Western Asia":
		fallthrough
	case "Eastern Europe":
		fallthrough
	case "Northern Europe":
		fallthrough
	case "Southern Europe":
		fallthrough
	case "Western Europe":
		fallthrough
	case "Australia and New Zealand":
		fallthrough
	case "Melanesia":
		fallthrough
	case "Micronesia":
		fallthrough
	case "Polynesia":
		*e = RegionName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RegionName: %v", v)
	}
}
