// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TLSCertificateIssuer struct {
	// The issuer's country.
	C string `json:"C"`
	// The issuer's common name.
	Cn string `json:"CN"`
	// The issuer's organization.
	O string `json:"O"`
}

func (o *TLSCertificateIssuer) GetC() string {
	if o == nil {
		return ""
	}
	return o.C
}

func (o *TLSCertificateIssuer) GetCn() string {
	if o == nil {
		return ""
	}
	return o.Cn
}

func (o *TLSCertificateIssuer) GetO() string {
	if o == nil {
		return ""
	}
	return o.O
}
