// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TLSCertificateSubject struct {
	// The subject's common name.
	Cn string `json:"CN"`
	// The subject's alternative names.
	Alt string `json:"alt"`
}

func (o *TLSCertificateSubject) GetCn() string {
	if o == nil {
		return ""
	}
	return o.Cn
}

func (o *TLSCertificateSubject) GetAlt() string {
	if o == nil {
		return ""
	}
	return o.Alt
}
